### ISSUE TITLE
Login command sometimes does not type the full username

### ISSUE THREAD

**Issue by cadic** [10up/cypress-wp-utils#11]
### Describe the bug

When running intensive tests, the `login` command sometimes fail to type full username. For admin it could be `min`, `n`, `in` or even an empty string.

Looks like typing starts before the input get focus.

### Steps to Reproduce

Check artifacts from the recent tests:
[cypress-artifact (3).zip](https://github.com/10up/cypress-wp-utils/files/8216146/cypress-artifact.3.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
It's still happening sometimes in minimum and trunk env.

**Comment by dinhtungdu** [comment]
@iamdharmesh Simple Podcasting has [a slightly different login command](https://github.com/10up/simple-podcasting/blob/da4f362917f61c2095fc5c9fa58a50622a4372ae/tests/cypress/support/commands.js#L29-L41), can you try it to see if it fixes the flaky issue? 

There is another workaround is [using a timeout](https://github.com/tschortsch/cypress-wp-test-utils/blob/a33347529eb7e8303c001a7c0327c7034053964a/src/commands/login-user.ts#L15-L17).

**Comment by iamdharmesh** [comment]
Hi @dinhtungdu, Thanks for pointing out the solution. `Simple Podcasting`'s login command seems working fine for me(Tried multiple runs, all are passed).

Also, Yesterday I tried to fix this with jQuery's `val` function, by creating a custom child command, and it's worked. please check the code below. If you think this is a good way, then we can add this `setValue` command to lib and can use it directly when we face this flaky issue anywhere. what do you think?
```
Cypress.Commands.add('setValue', {prevSubject: true}, (subject, text) => {
    subject.val(text);
    return cy.wrap(subject);
});


Cypress.Commands.add( 'login', (username = 'admin', password = 'password') => {
	cy.visit('wp-login.php');
	cy.get('input#user_login').should('be.visible').setValue(username);
	cy.get('input#user_pass').should('be.visible').setValue(password).type('{enter}');
});
```
