### ISSUE TITLE
`clearThenType`

### ISSUE THREAD

**Issue by dinhtungdu** [10up/cypress-wp-utils#18]

**Comment by iamdharmesh** [comment]
Hi @dinhtungdu @cadic, 

Considering Cypress Best Practices [here](https://docs.cypress.io/api/cypress-api/custom-commands#2-Don-t-overcomplicate-things), I am not sure if we should add this command to this lib or not. 
`cy.get().clear().type()` vs `cy.get().clearThenType()`

This is a great command to add for specific plugin tests, but I don't think it is good to add in this lib. what do you think?

Thanks.

**Comment by dinhtungdu** [comment]
I agree! I actually prefer `cy.get().clear().type()` over the other.

**Comment by cadic** [comment]
I agree that this command is overcomplicating things. Closing this.
