### ISSUE TITLE
Migrate existing test commands to this library

### ISSUE THREAD

**Issue by dinhtungdu** [10up/cypress-wp-utils#4]
### Is your enhancement related to a problem? Please describe.

Before this library, we've added Cypress for some of the 10up open-source plugins. We're adding custom commands directly in `cypress/support/commands.js` for those plugins. We're should migrate commands from those plugins into this library:

- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #38

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
Closing this as all child items are completed
