### ISSUE TITLE
Upgrade to Cypress 12

### ISSUE THREAD

**Issue by cadic** [10up/cypress-wp-utils#83]
### Is your enhancement related to a problem? Please describe.

Cypress 12 was released and already received a few minor updates. Need to test the library against the latest version and fix issues if there are any.

### Breaking changes we need to be aware of

- Cypress dropped support for Node.js 12
- In Cypress 12, we enforce running tests in a clean browser context through [test isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation).
- The `Cookies.defaults` and `Cookies.preserveOnce` APIs have been removed. Use the new [cy.session()](https://docs.cypress.io/api/commands/session) command to preserve cookies between tests. Looks like we now forced to update our login/logout commands, #55 is unblocked.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
We may want to consider tagging/releasing 0.1.0 and afterwards merging an update here so that projects using older versions of Cypress can utilize v0.1.0 but newer Cypress versions can use >v0.1.0 once we tag another version newer than v0.1.0.
